version: "3.3"
services:
  api:
    depends_on:
      - db
    ports:
      - "8080:8080"
    build: .
    volumes:
      - "$HOME/docker/volumes/api:${FILESTORAGE}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      FILES_STORAGE_URL: ${FILESTORAGEURL}
      UPLOAD_DEFAULT_PATH: ${FILESTORAGE}
  db:
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - "$HOME/docker/volumes/postgres:/var/lib/postgresql/"

