name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub login
        run: docker login --username ${{ secrets.USERNAME_HUB }} --password ${{ secrets.PASSWORD_HUB }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package -D spring.profiles.active=test
      - name: Build Docker
        run: docker build --tag ${{ secrets.USERNAME_HUB }}/cinema-back:latest .
      - name: Push into DockerHub
        run: docker push ${{ secrets.USERNAME_HUB }}/cinema-back:latest